version: '3.1'
services:
  db:
    build:
      context: src/
      dockerfile: dockerfile_db
    restart:
      always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sncf"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    expose:
      - "3306"
    networks:
      - networks_PHP

  httpdserver:
    depends_on:
      - db
    build:
      context: src/
      dockerfile: dockerfile_web

    ports:
      - 80:80
    networks:
      - networks_PHP
networks:
  networks_PHP:
    driver:
      bridge
