apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  selector:
    app: db
  clusterIP: None
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
  selector:
          app: web
  sessionAffinity: ClientIP
